const router = require('express').Router();
const axios = require('axios');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const db = require('../db/database');
const { addHotspotUser, removeHotspotUser, disconnectHotspotUser } = require('../mikrotik/mikrotik');
const PROFILE_MAP = {1:'research-daily',2:'research-weekly',3:'research-monthly',4:'basic-daily',5:'basic-weekly',6:'basic-monthly',7:'premium-daily',8:'premium-weekly',9:'premium-monthly',10:'vip-daily',11:'vip-weekly',12:'vip-monthly'};
const baseUrl=()=>String(process.env.PUBLIC_BASE_URL||'').replace(/\/$/,'');
const appSecret=()=>process.env.APP_ENCRYPTION_KEY||process.env.ADMIN_API_KEY||'change-this-before-production';
const key=()=>crypto.createHash('sha256').update(appSecret()).digest();
const token=id=>`${id}.${crypto.createHmac('sha256',appSecret()).update(String(id)).digest('hex')}`;
function readToken(value){const [id,sig]=String(value||'').split('.'),valid=crypto.createHmac('sha256',appSecret()).update(String(id)).digest('hex');return id&&sig&&crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(valid))?Number(id):0;}
function encrypt(value){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),body=Buffer.concat([c.update(value,'utf8'),c.final()]),tag=c.getAuthTag();return `${iv.toString('base64')}.${tag.toString('base64')}.${body.toString('base64')}`;}
function decrypt(value){const [iv,tag,body]=String(value||'').split('.').map(x=>Buffer.from(x,'base64')),d=crypto.createDecipheriv('aes-256-gcm',key(),iv);d.setAuthTag(tag);return Buffer.concat([d.update(body),d.final()]).toString('utf8');}
const isReady=()=>Boolean(process.env.PAYSTACK_SECRET_KEY&&baseUrl());
async function account(req){const id=readToken(req.headers['x-account-token']||req.body?.account_token);return id?db.getAsync('SELECT * FROM users WHERE id=?',[id]):null;}

router.post('/account',async(req,res)=>{const {email,password,confirm_password:confirm}=req.body||{},mail=String(email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(mail)||String(password||'').length<6)return res.status(400).json({error:'Enter a valid email and password of at least 6 characters.'});let user=await db.getAsync('SELECT * FROM users WHERE email=? OR username=?',[mail,mail]);if(user){if(!(await bcrypt.compare(password,user.password).catch(()=>false)))return res.status(401).json({error:'Incorrect email or password.'});}else{if(confirm!==password)return res.status(400).json({error:'Password confirmation does not match.'});const x=await db.runAsync('INSERT INTO users(username,password,email,hotspot_password_hash,status) VALUES(?,?,?,?,?)',[mail,await bcrypt.hash(password,10),mail,encrypt(password),'INACTIVE']);user=await db.getAsync('SELECT * FROM users WHERE id=?',[x.lastID]);}res.json({account_token:token(user.id),user:{email:user.email||user.username,status:user.status}});});
router.get('/packages',async(_q,res)=>res.json({packages:await db.allAsync('SELECT id,name,speed,duration_days,data_cap,data_cap_bytes,price FROM packages ORDER BY id')}));

router.post('/initialize',async(req,res)=>{const user=await account(req),packageId=Number(req.body?.package_id);if(!user)return res.status(401).json({error:'Please sign in again.'});const pkg=await db.getAsync('SELECT * FROM packages WHERE id=?',[packageId]);if(!pkg||!PROFILE_MAP[pkg.id])return res.status(400).json({error:'Selected package is unavailable.'});if(!isReady())return res.status(503).json({error:'Online payment is not configured yet. Please use a voucher for now.'});const reference=`SW-${Date.now()}-${crypto.randomBytes(5).toString('hex')}`,callback=new URL(`${baseUrl()}/payment/callback`);if(req.body?.router_login)callback.searchParams.set('router-login',req.body.router_login);if(req.body?.dst)callback.searchParams.set('dst',req.body.dst);await db.runAsync('INSERT INTO transactions(user_id,package_id,amount,paystack_reference,status) VALUES(?,?,?,?,?)',[user.id,pkg.id,pkg.price,reference,'pending']);try{const r=await axios.post('https://api.paystack.co/transaction/initialize',{email:user.email||user.username,amount:Math.round(Number(pkg.price)*100),currency:'GHS',reference,callback_url:callback.toString(),channels:['mobile_money'],metadata:{user_id:user.id,package_id:pkg.id}},{headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`},timeout:20000});if(!r.data?.status||!r.data?.data?.authorization_url)throw new Error(r.data?.message||'Paystack could not initialize payment.');res.json({authorization_url:r.data.data.authorization_url,reference});}catch(e){await db.runAsync("UPDATE transactions SET status='initialize_failed' WHERE paystack_reference=?",[reference]);res.status(502).json({error:e.response?.data?.message||e.message||'Unable to start payment.'});}});

async function grant(reference){const t=await db.getAsync('SELECT t.*,u.hotspot_username,u.hotspot_password_hash,p.duration_days,p.data_cap_bytes,p.id package_id FROM transactions t JOIN users u ON u.id=t.user_id JOIN packages p ON p.id=t.package_id WHERE t.paystack_reference=?',[reference]);if(!t)throw new Error('Transaction not found.');if(t.status==='success'&&t.access_granted_at)return t;const check=await axios.get(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`},timeout:20000}),paid=check.data?.data;if(!check.data?.status||paid?.status!=='success'||Number(paid.amount)!==Math.round(Number(t.amount)*100))throw new Error('Payment has not been confirmed yet.');const username=t.hotspot_username||`SW${t.user_id}`,password=decrypt(t.hotspot_password_hash),expiresAt=new Date(Date.now()+Number(t.duration_days)*86400000).toISOString();try{await disconnectHotspotUser(username);await removeHotspotUser(username);}catch(_){/* first purchase */}await addHotspotUser(username,password,PROFILE_MAP[t.package_id],t.data_cap_bytes,`${t.duration_days}d`);await db.runAsync('BEGIN IMMEDIATE');try{await db.runAsync("UPDATE transactions SET status='success',paid_at=COALESCE(paid_at,CURRENT_TIMESTAMP),payment_channel=?,access_granted_at=COALESCE(access_granted_at,CURRENT_TIMESTAMP) WHERE id=?",[paid.channel||'mobile_money',t.id]);await db.runAsync("UPDATE users SET hotspot_username=?,active_package_id=?,package_expires_at=?,status='ACTIVE' WHERE id=?",[username,t.package_id,expiresAt,t.user_id]);await db.runAsync("UPDATE sessions SET status='expired',end_time=CURRENT_TIMESTAMP WHERE user_id=? AND status='active'",[t.user_id]);await db.runAsync("INSERT INTO sessions(user_id,hotspot_username,package_id,expires_at,status) VALUES(?,?,?,?, 'active')",[t.user_id,username,t.package_id,expiresAt]);await db.runAsync('COMMIT');}catch(e){await db.runAsync('ROLLBACK');throw e;}return {...t,hotspot_username:username,expires_at:expiresAt,_password:password};}
router.post('/verify',async(req,res)=>{if(!isReady())return res.status(503).json({error:'Online payment is not configured yet.'});try{const r=await grant(req.body?.reference);res.json({message:'Payment confirmed. Connecting you now.',username:r.hotspot_username,password:r._password,expires_at:r.expires_at});}catch(e){res.status(409).json({error:e.message||'Unable to confirm payment.'});}});
router.post('/webhook',(req,res)=>{const signature=req.headers['x-paystack-signature'],expected=process.env.PAYSTACK_SECRET_KEY?crypto.createHmac('sha512',process.env.PAYSTACK_SECRET_KEY).update(JSON.stringify(req.body)).digest('hex'):'';if(!signature||!expected||!crypto.timingSafeEqual(Buffer.from(String(signature)),Buffer.from(expected)))return res.status(401).send('Invalid signature');res.sendStatus(200);if(req.body?.event==='charge.success'&&req.body?.data?.reference)grant(req.body.data.reference).catch(e=>console.error('[paystack/webhook]',e.message));});
module.exports=router;
